service: ax1-dian

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(../../env.${self:provider.stage}.yml)}

plugins:
  - serverless-plugin-typescript

functions:
  auth:
    name: ${self:service}-auth-${self:provider.stage}
    handler: auth/index.handler
